ALTER TABLE TOTALTST.AD_LOGDISTCARTEIRA
 DROP PRIMARY KEY CASCADE;

DROP TABLE TOTALTST.AD_LOGDISTCARTEIRA CASCADE CONSTRAINTS;

CREATE TABLE TOTALTST.AD_LOGDISTCARTEIRA
(
  ID             NUMBER(10)                     NOT NULL,
  DTHRALTER      DATE,
  CODPARC        NUMBER(10),
  CODVENDNOVO    NUMBER(5),
  CODUSU         NUMBER(5),
  CODVENDANTIGO  NUMBER(5),
  TIPO           VARCHAR2(10 BYTE),
  CODREG         NUMBER(10),
  RESTOR         NUMBER(10)
)
TABLESPACE TOTALDADOS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TOTALTST.PK_AD_LOGDISTCARTEIRA ON TOTALTST.AD_LOGDISTCARTEIRA
(ID)
LOGGING
TABLESPACE TOTALDADOS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TOTALTST.AD_LOGDISTCARTEIRA ADD (
  CONSTRAINT PK_AD_LOGDISTCARTEIRA
  PRIMARY KEY
  (ID)
  USING INDEX TOTALTST.PK_AD_LOGDISTCARTEIRA
  ENABLE VALIDATE);

ALTER TABLE TOTALTST.AD_LOGDISTCARTEIRA ADD (
  CONSTRAINT AD_FK_DA1E716543762240BA1FC 
  FOREIGN KEY (CODVENDANTIGO) 
  REFERENCES TOTALTST.TGFVEN (CODVEND)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_DFD3F165439475A34D6BA 
  FOREIGN KEY (CODREG) 
  REFERENCES TOTALTST.TSIREG (CODREG)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_2AA141651F3CBE71A7891 
  FOREIGN KEY (CODVENDNOVO) 
  REFERENCES TOTALTST.TGFVEN (CODVEND)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_5CE111651F3D0522F1D95 
  FOREIGN KEY (CODUSU) 
  REFERENCES TOTALTST.TSIUSU (CODUSU)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_6C5FE1651F3C173C9A783 
  FOREIGN KEY (CODPARC) 
  REFERENCES TOTALTST.TGFPAR (CODPARC)
  ENABLE VALIDATE);
