SELECT (SELECT GRU.DESCRGRUPOPROD FROM TGFGRU GRU WHERE GRU.CODGRUPOPROD = (SELECT GRU.CODGRUPAI FROM TGFGRU GRU WHERE GRU.CODGRUPOPROD = GRUPO)) AS DESCGRUPOPAI
     , (SELECT GRU.DESCRGRUPOPROD FROM TGFGRU GRU WHERE GRU.CODGRUPOPROD = GRUPO) AS DESCGRUPO
     --SELECT * FROM TGFGRU 
     , GRUPO
     , SUM(PERC) AS PERCENTUAL
     , ADD_MONTHS (TO_DATE (TRUNC (ADD_MONTHS (TO_DATE (TRUNC (TO_DATE(SYSDATE, 'DD/MM/YYYY'),'MONTH'),'DD/MM/YY'),-11),'MONTH'),'DD/MM/YY'),-1)
        || ' - ' || ADD_MONTHS (TO_DATE (LAST_DAY (TO_DATE(SYSDATE, 'DD/MM/YYYY')),'DD/MM/YYYY'),-12) AS TESTE

FROM(
     SELECT GRUPO
          , PERC
     FROM (
           SELECT GRUPO
                , TOTAL_NOTA
                , TOTAL
                , ROUND((TOTAL_NOTA / TOTAL) * 100,4) AS PERC
           FROM (
                 SELECT PRO.CODGRUPOPROD AS GRUPO,
                        SUM(ITE.VLRTOT) AS TOTAL_NOTA,
                        (SELECT SUM(TT) AS TOTAL
                            FROM (SELECT PRO.CODGRUPOPROD,
                                        SUM(ITE.VLRTOT) AS TT
                                FROM TGFITE ITE INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
                                                INNER JOIN TGFCAB CAB ON (CAB.NUNOTA = ITE.NUNOTA)
                                WHERE TRUNC(CAB.DTFATUR) BETWEEN ADD_MONTHS (TO_DATE (TRUNC (ADD_MONTHS (TO_DATE (TRUNC (TO_DATE(SYSDATE, 'DD/MM/YYYY'),'MONTH'),'DD/MM/YY'),-11),'MONTH'),'DD/MM/YY'),-1)
                                                                 AND ADD_MONTHS (TO_DATE (LAST_DAY (TO_DATE(SYSDATE, 'DD/MM/YYYY')),'DD/MM/YY'),-12) 
                                    AND CAB.CODTIPOPER = 3200
                            AND CAB.STATUSNFE = 'A'
                                GROUP BY PRO.CODGRUPOPROD)) as total  
                 FROM TGFITE ITE INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
                        INNER JOIN TGFCAB CAB ON (CAB.NUNOTA = ITE.NUNOTA)
                 WHERE TRUNC(CAB.DTFATUR) BETWEEN ADD_MONTHS (TO_DATE (TRUNC (ADD_MONTHS (TO_DATE (TRUNC (TO_DATE(SYSDATE, 'DD/MM/YYYY'),'MONTH'),'DD/MM/YY'),-11),'MONTH'),'DD/MM/YY'),-1)
                                                  AND ADD_MONTHS (TO_DATE (LAST_DAY (TO_DATE(SYSDATE, 'DD/MM/YYYY')),'DD/MM/YY'),-12)
                   AND CAB.CODTIPOPER = 3200
                   AND CAB.STATUSNFE = 'A' 
                 GROUP BY PRO.CODGRUPOPROD
                 ORDER BY TOTAL_NOTA)
            ORDER BY PERC, GRUPO)

    UNION ALL

        SELECT GRU.CODGRUPOPROD AS GRUPO
            , 0 AS PERC
        FROM TGFGRU GRU
        WHERE GRU.ANALITICO = 'S'
        AND ATIVO = 'S'
        AND GRU.CODGRUPAI NOT LIKE '50%'
        AND GRU.CODGRUPAI NOT LIKE '90%'
        AND GRU.CODGRUPAI NOT LIKE '91%'
        AND GRU.CODGRUPAI NOT LIKE '92%'
        AND GRU.CODGRUPAI NOT LIKE '93%'
        AND GRU.CODGRUPAI NOT LIKE '94%'
        AND GRU.CODGRUPAI NOT LIKE '95%'
        AND GRU.CODGRUPAI NOT LIKE '96%'
        AND GRU.CODGRUPAI NOT LIKE '97%'
        AND GRU.CODGRUPAI NOT LIKE '98%'
        AND GRU.CODGRUPOPROD NOT IN (0, 60000000))
GROUP BY GRUPO
ORDER BY PERCENTUAL, DESCGRUPO
;