UPDATE TSIRLG AA SET LOGOUT = SYSDATE WHERE AA.CODUSU = 
(SELECT R.CODUSU
FROM TSIRLG R 
WHERE R.CODUSU = AA.CODUSU
  AND R.SEQACESSO = AA.SEQACESSO
  AND R.LOGOUT IS NULL 
  AND R.CODUSU IN (SELECT R.CODUSU FROM TSIRLG R WHERE R.LOGIN > SYSDATE -1) 
  AND R.LOGIN > SYSDATE -1 AND (SYSDATE - R.LOGIN) NOT IN 
  (SELECT MAX(SYSDATE - RR.LOGIN) FROM TSIRLG  RR WHERE RR.CODUSU = R.CODUSU AND RR.LOGIN > SYSDATE -1))
AND AA.SEQACESSO = 
(SELECT R.SEQACESSO
FROM TSIRLG R 
WHERE R.CODUSU = AA.CODUSU 
  AND R.SEQACESSO = AA.SEQACESSO
  AND R.LOGOUT IS NULL
  AND R.CODUSU IN (SELECT R.CODUSU FROM TSIRLG R WHERE R.LOGIN > SYSDATE -1) 
  AND R.LOGIN > SYSDATE -1 AND (SYSDATE - R.LOGIN) NOT IN 
  (SELECT MAX(SYSDATE - RR.LOGIN) FROM TSIRLG  RR WHERE RR.CODUSU = R.CODUSU AND RR.LOGIN > SYSDATE -1));


SELECT * FROM TSIRLG R WHERE R.LOGIN > SYSDATE -1 AND R.LOGOUT IS NULL